
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(pracma)
library(corpcor)
library(purrr)
library(plotly)
library(dplyr)
library(tidyr)
library(Matrix)
library(rafalib)
library(readxl)
library(moments)
library(tseries)


data1 <- read_excel("FundData.xls", sheet = 1)
data2 <- read_excel("FundData.xls", sheet = 2)
data3 <- read_excel("FundData.xls", sheet = 3)


x1 = as.Date(as.character(data1$caldt), "%Y%m%d")
x2 = as.Date(as.character(data2$caldt), "%Y%m%d")
x3 = as.Date(as.character(data3$caldt), "%Y%m%d")
```





```{r}
ff <- read.csv("F-F_Research_Data_Factors.CSV")
exretMkt <- ff$Mkt.RF[854:1122]/100
SMB <- ff$SMB[854:1122]/100
HML <- ff$HML[854:1122]/100
f <- ff$RF[854:1122]/100
exmretfund <- as.double(data2$mret[3:271]) - f
df <- data.frame(exmretfund, exretMkt, SMB, HML)


qrgivens <- function(A, y){
  m = nrow(A)
  n = ncol(A)
  Q = eye(m)
  R = A
  for (j in 1:n){
    for (i in seq(m, j + 1)){
      G = eye(m)
      res = givensrotation(R[i-1,j], R[i,j])
      c = res[1]
      s = res[2]
      mm = matrix(c(c, -s, s, c), nrow=2, ncol=2, byrow = TRUE)
      G[c(i-1, i),c(i-1, i)] = mm
      R = t(G) %*% R
      Q = Q %*% G
    }
  }
  Qty <- as.numeric(crossprod(Q, y))
  ## solving upper triangular system
  b <- backsolve(R, Qty)
  ## residuals
  e <- as.numeric(y - A %*% b)
  ## R-squared
  RSS <- crossprod(e)[1]
  TSS <- crossprod(y - mean(y))[1]
  R2 <- 1 - RSS / TSS
  ## multiple return
  list(coefficients = b, R2 = R2)
}




givensrotation <- function(a,b) {
  if (b == 0){
    c = 1
    s = 0
  }else {
    if (abs(b) > abs(a)){
      r = a/b
      s = 1 / sqrt(1 + r*r);
      c = s*r;
    } else{
      r = b/a
      c = 1 / sqrt(1 + r*r);
      s = c*r;
    }
  }
  return(c(c, s))
}




HouseholderRefl <- function(A, y) {
  n <- ncol(A)
  m <- nrow(A)
  H <- list() #to store the H_k matrices
  R <- as.matrix(A) 
  
  if (m > n) {
    l <- n
  } 
  else {
    l <- m
  }
  for (k in 1:l) {
    x <- R[k:m, k]
    e <- as.matrix(c(1, rep(0, length(x)-1)))
    v_k <- sign(x[1]) * sqrt(sum(x^2)) * e + x
    
    H_k <- diag(length(x)) - 2 * as.vector(v_k %*% t(v_k)) / (t(v_k) %*% v_k)
    if (k > 1) {
      H_k <- bdiag(diag(k-1), H_k)
    }
    H[[k]] <- H_k
    R <- H_k %*% R
  }
  
  Q <- Reduce("%*%", H) 
  R <- as.matrix(R) 
  
  Qty <- as.numeric(crossprod(Q, y))
  ## solving upper triangular system
  b <- backsolve(R, Qty)
  ## residuals
  e <- as.numeric(y - A %*% b)
  ## R-squared
  RSS <- crossprod(e)[1]
  TSS <- crossprod(y - mean(y))[1]
  R2 <- 1 - RSS / TSS
  ## multiple return
  list(coefficients = b, R2 = R2)
}





gramschmidt <- function(x, y) {
  #x <- as.matrix(x)
  # Get the number of rows and columns of the matrix
  n <- ncol(x)
  m <- nrow(x)
  
  # Initialize the Q and R matrices
  q <- matrix(0, m, n)
  r <- matrix(0, n, n)
  
  for (j in 1:n) {
    v = x[,j] # Step 1 of the Gram-Schmidt process v1 = a1
    # Skip the first column
    if (j > 1) {
      for (i in 1:(j-1)) {
        r[i,j] <- t(q[,i]) %*% x[,j] # Find the inner product (noted to be q^T a earlier)
        # Subtract the projection from v which causes v to become perpendicular to all columns of Q
        v <- v - r[i,j] * q[,i] 
      }      
    }
    # Find the L2 norm of the jth diagonal of R
    r[j,j] <- sqrt(sum(v^2))
    # The orthogonalized result is found and stored in the ith column of Q.
    q[,j] <- v / r[j,j]
  }
  
  Qty <- as.numeric(crossprod(q, y))
  ## solving upper triangular system
  b <- backsolve(r, Qty)
  ## residuals
  e <- as.numeric(y - x %*% b)
  ## R-squared
  RSS <- crossprod(e)[1]
  TSS <- crossprod(y - mean(y))[1]
  R2 <- 1 - RSS / TSS
  ## multiple return
  list(coefficients = b, R2 = R2)
}







r <- data.frame(df$exretMkt, df$SMB, df$HML)
d <- data.matrix(r)

gramschmidt(d, df$exmretfund)
qrgivens(d, df$exmretfund)
HouseholderRefl(d, df$exmretfund)



summary(ols <- lm(exmretfund ~ exretMkt + SMB + HML, data = df))
```














#Comparing time efficiency of each method
```{r}
qrgivens <- function(A){
  m = nrow(A)
  n = ncol(A)
  Q = eye(m)
  R = A
  for (j in 1:n){
    for (i in seq(m, j + 1)){
      G = eye(m)
      res = givensrotation(R[i-1,j], R[i,j])
      c = res[1]
      s = res[2]
      mm = matrix(c(c, -s, s, c), nrow=2, ncol=2, byrow = TRUE)
      G[c(i-1, i),c(i-1, i)] = mm
      R = t(G) %*% R
      Q = Q %*% G
    }
  }
}




givensrotation <- function(a,b) {
  if (b == 0){
    c = 1
    s = 0
  }else {
    if (abs(b) > abs(a)){
      r = a/b
      s = 1 / sqrt(1 + r*r);
      c = s*r;
    } else{
      r = b/a
      c = 1 / sqrt(1 + r*r);
      s = c*r;
    }
  }
  return(c(c, s))
}





gramschmidt <- function(x) {
  #x <- as.matrix(x)
  # Get the number of rows and columns of the matrix
  n <- ncol(x)
  m <- nrow(x)
  
  # Initialize the Q and R matrices
  q <- matrix(0, m, n)
  r <- matrix(0, n, n)
  
  for (j in 1:n) {
    v = x[,j] # Step 1 of the Gram-Schmidt process v1 = a1
    # Skip the first column
    if (j > 1) {
      for (i in 1:(j-1)) {
        r[i,j] <- t(q[,i]) %*% x[,j] # Find the inner product (noted to be q^T a earlier)
        # Subtract the projection from v which causes v to become perpendicular to all columns of Q
        v <- v - r[i,j] * q[,i] 
      }      
    }
    # Find the L2 norm of the jth diagonal of R
    r[j,j] <- sqrt(sum(v^2))
    # The orthogonalized result is found and stored in the ith column of Q.
    q[,j] <- v / r[j,j]
  }
}




HouseholderRefl <- function(A, y) {
  n <- ncol(A)
  m <- nrow(A)
  H <- list() #to store the H_k matrices
  R <- as.matrix(A) 
  
  if (m > n) {
    l <- n
  } 
  else {
    l <- m
  }
  for (k in 1:l) {
    x <- R[k:m, k]
    e <- as.matrix(c(1, rep(0, length(x)-1)))
    v_k <- sign(x[1]) * sqrt(sum(x^2)) * e + x
    
    H_k <- diag(length(x)) - 2 * as.vector(v_k %*% t(v_k)) / (t(v_k) %*% v_k)
    if (k > 1) {
      H_k <- bdiag(diag(k-1), H_k)
    }
    H[[k]] <- H_k
    R <- H_k %*% R
  }
  
  Q <- Reduce("%*%", H) 
}







QR_comp = function(A){
  t0 = Sys.time()
  qrgivens(A)
  Givens = Sys.time() - t0
  
  t0 = Sys.time()
  gramschmidt(A)
  Gram_Schmidt = Sys.time() - t0
  
  
  t0 = Sys.time()
  HouseholderRefl(A)
  Householder = Sys.time() - t0
  
  return(data.frame(Givens = as.numeric(Givens), Gram_Schmidt = as.numeric(Gram_Schmidt), Householder = as.numeric(Householder)))
}




n <- c()
m <- c()

for (n1 in seq(1,52, by=2)){
  for (m1 in seq((n1+1),53, by=2)){
    n <- append(n, n1)
    m <- append(m, m1)

  }
}





tvec = map2(m, n, ~QR_comp(matrix(runif(.x*.y), ncol = .y)))


plotly::ggplotly(
bind_rows(tvec) %>%
  gather("func","time") %>%
  mutate(n = rep(n, 3), m = rep(m, 3)) %>%
  ggplot(aes(m, n, fill = time)) + 
  geom_tile() + 
  facet_grid(.~func) +
  scale_fill_gradientn(colours = rainbow(9)) +
  theme(panel.background = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_text(angle = 35, size = 5),
        axis.text.x = element_text(angle = 30, size = 5)), width = 550, heigh = 400)



```


